server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
      min: 8
      max: 200
  port: 8094
  servlet:
    context-path: /hospital-api

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hospital_mysql?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
#    password: abc123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  quartz:
    job-store-type: memory

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.hospital.api.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.hospital.api.db.dao: warn
  pattern:
    console: "%d{yyyy/MM/dd HH:mm:ss}  %-5level  %msg%n"

sa-token:
  token-name: token
  timeout: 2592000
  activity-timeout: -1
  allow-concurrent-login: true
  is-share: false
  token-style: uuid
  isReadCookie: false

#
#wechat:
#  app-id: 你的微信小程序APPID
#  app-secret: 你的微信小程序密钥
#  pay:
#    v3:
#      patient-wx-api:
#        app-id: 你的微信小程序APPID
#        app-v3-secret: 微信商户平台密钥
#        mch-id: 微信商户平台ID
#        domain: http://内网穿透的外网IP地址和端口/hospital-wx-api
#        cert-path: apiclient_cert.p12
#
tencent:
  cloud:
    appId: 1308222269
    secretId: AKID3zf7b4Skv7AzZyGVar8KRixNC9eJzhRK
    secretKey: zut273qVxDGIOTOLGA527KPPFqGWZSDn
    face:
      groupName: hospital
      region: ap-beijing
  trtc:
    appId: 1600018532
    secretKey: 196c9dc9e34ea1ef27c4c25c917569cff3aa5f65b5d6006134a578ee59f78321
    expire: 86400
minio:
  endpoint: http://62.234.37.187:9000
  access-key: root
  secret-key: abc123456

